name: 'ESLint checker'
author: 'Valentin Hisari <hisari.valentin@gmail.com>'
description: 'Check if changed files are properly formatted by the provided eslint rules.'
inputs:
  repo-token:
    description: 'github security token'
    required: true
  custom-directory:
    description: 'relative directory to node_modules'
    required: true
  eslint-config-path:
    description: 'relative path to eslint config file eg. .eslintrc'
    required: true
  eslint-ignore-rules:
    description: 'rules to ignore separated by , eg. "import/prefer-default-export,jsx-a11y/label-has-for"'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'

