name: Node CI

on: [push]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install eslint globally
      run:
        npm i eslint -g

    - name: npm install
      run: npm ci
      env:
        CI: true

    - name: Run ESLint
      uses: ninosaurus/eslint-check@master
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
